Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./output
  save_interval: 1
  eval_during_train: False
  epochs: 50
  print_batch_step: 10
  use_visualdl: False
  image_shape: [3, 512, 96]
  save_inference_dir: ./inference
  eval_interval: 1
  pretrained: True
  class_num: 2  # roll and yaw
  save_epoch_step: 1
  device: cpu

Arch:
  name: "PPLCNetV2_base"
  pretrained: True
  class_num: 2

DataLoader:
  Train:
    dataset:
      name: "AngleDataset"
      image_root: "./smooth_angle_dataset"
      cls_label_path: "./smooth_angle_dataset/label.txt"
      transform_ops:
        - ToCHWImage:
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
    sampler:
      name: "BatchSampler"
      batch_size: 8
      drop_last: False
      shuffle: True
    loader:
      num_workers: 16
      use_shared_memory: True

  Eval:
    dataset:
      name: "AngleDataset"
      image_root: "./smooth_angle_dataset"
      cls_label_path: "./smooth_angle_dataset/label.txt"
      transform_ops:
        - ToCHWImage:
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
    sampler:
      name: "BatchSampler"
      batch_size: 8
      drop_last: False
      shuffle: False
    loader:
      num_workers: 8
      use_shared_memory: True

Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: Cosine
    learning_rate: 0.05
    warmup_epoch: 5
  regularizer:
    name: 'L2'
    coeff: 0.00001


Loss:
  Train:
    - MSELoss:
        weight: 1.0
  Eval:
    - MSELoss:
        weight: 1.0

Metrics:
  Train:
    - MSE
  Eval:
    - MSE
